# Generated by Django 6.0.7 on 2026-09-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_experiments_carry_their_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='priors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
