# Generated by Django 6.0.7 on 2026-10-01 10:42

import django.db.models.deletion
import ui.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0028_deleting_puts_work_in_its_peoples_bins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_figure_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FigureLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', ui.fields.SafeJSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_layouts', to='ui.experiment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figure_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('experiment', 'user'), name='one_layout_per_reader_per_experiment'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('experiment',), name='one_layout_per_experiment_without_accounts')],
            },
        ),
    ]
