# Generated by Django 6.0.7 on 2026-10-01 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0030_default_figure_layouts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_figure_layout',
        ),
        migrations.AlterField(
            model_name='defaultfigurelayout',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_figure_layout', to=settings.AUTH_USER_MODEL),
        ),
    ]
