# Generated by Django 6.1.1 on 2026-10-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0033_experiment_time_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='horizon',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='season',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='series_column',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
