# Generated by Django 6.1.1 on 2026-10-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0035_experiment_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='demo_dataset',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='TrialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('directory', models.CharField(max_length=500)),
                ('bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_models', to='ui.experiment')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_models', to='ui.run')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('experiment', 'trial'), name='one_kept_model_per_trial')],
            },
        ),
    ]
