# Generated by Django 6.0.7 on 2026-10-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def queued_when_started(apps, schema_editor):
    """A run from before queueing was recorded was queued no later than it
    started, which is the nearest thing there is to when."""
    Run = apps.get_model("ui", "Run")
    Run.objects.filter(created_at__isnull=True).update(created_at=models.F("started_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0037_demo_datasets_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(queued_when_started, migrations.RunPython.noop),
    ]
