# Generated by Django 6.0.7 on 2026-09-25 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_groups_take_over'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('lead', 'Group lead'), ('primary_lead', 'Primary group lead')], default='member', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary_lead')), fields=('group',), name='one_primary_lead_per_group'),
        ),
    ]
