# Generated by Django 6.1.1 on 2026-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_every_account_is_found_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='storage_limit_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
